name: Run Azure Login with OpenID Connected
on:
  schedule:
    - cron: '*/30 * * * *'
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          # creds: ${{secrets.AZURE_CREDENTIALS}}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 