name: Run Azure Login with OpenID Connected
on:
  push
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: 'Az CLI login'
      run: |
# az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_SECRET_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        uses: azure/login@v1
        with:
            # creds: ${{secrets.AZURE_CREDENTIALS}}
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Checkout repository code
      uses: actions/checkout@v4
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 
    - name: 'Settings'
      run: |
          az extension add -n ml
          az ml workspace list
    - name: 'Run Azure Pipeline'
      run: |
          az ml job create -f pipeline.yml -g case1-rg-common-jpe -w case1-mlw-common-jpe